doctrine:
    dbal:
        driver: pdo_mysql
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
            App\Accounts:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Accounts/Entity'
                prefix: 'App\Accounts\Entity'
                alias: App\Accounts
            App\Contacts:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Contacts/Entity'
                prefix: 'App\Contacts\Entity'
                alias: App\Contacts
            App\Transactions:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Transactions/Entity'
                prefix: 'App\Transactions\Entity'
                alias: App\Transactions