accounts_api_search:
    path: /api/accounts/search
    controller: \App\Controller\AccountController::apiSearch
    methods: POST
contacts_api_search:
    path: /api/contacts/search
    controller: \App\Controller\ContactController::apiSearch
    methods: POST
transactions_list:
    path: /
    controller: \App\Controller\TransactionController::list
    methods: GET
transactions_submit:
    path: /
    controller: \App\Controller\TransactionController::submitForm
    methods: POST
transactions_api_list:
    path: /api/transactions/list
    controller: \App\Controller\TransactionController::apiList
    methods: POST
transactions_api_detail:
    path: /api/transactions/detail
    controller: \App\Controller\TransactionController::apiDetail
    methods: POST
statement_trial_balance:
    path: /obratova_predvaha
    controller: \App\Controller\StatementController::trialBalance
    methods: GET
statement_trial_balance_api_compile:
    path: /api/statement/trial_balance/compile
    controller: \App\Controller\StatementController::trialBalanceCompile
    methods: POST
statement_account:
    path: /vypis_uctu/{year}/{account}
    defaults:
        year:
        account:
    controller: \App\Controller\StatementController::accountStatement
    methods: GET
