accounts_list:
    path: /ucty
    controller: \App\Controller\AccountController::list
    methods: GET
contacts_list:
    path: /kontakty
    controller: \App\Controller\ContactController::contacts
    methods: GET
transactions_list:
    path: /
    controller: \App\Controller\TransactionController::list
    methods: GET
transactions_submit:
    path: /
    controller: \App\Controller\TransactionController::submitForm
    methods: POST
statement_trial_balance:
    path: /obratova_predvaha/{id}
    controller: \App\Controller\StatementController::trialBalance
    defaults:
        id:
    methods: GET
statement_trial_balance_api_compile:
    path: /api/statement/trial_balance/compile
    controller: \App\Controller\StatementController::trialBalanceCompile
    methods: POST
statement_trial_balance_api_list:
    path: /api/statement/trial_balance/list
    controller: \App\Controller\StatementController::trialBalanceList
    methods: GET
statement_trial_balance_api_remove:
    path: /api/statement/trial_balance/remove/{id}
    controller: \App\Controller\StatementController::trialBalanceRemove
    defaults:
        id:
    methods: GET
statement_account:
    path: /vypis_uctu/{year}/{account}
    defaults:
        year:
        account:
    controller: \App\Controller\StatementController::accountStatement
    methods: GET
statement_vat_generate:
    path: /api/statement/vat/inspectional/generate/{year}/{month}
    defaults:
        year:
        month:
    controller: \App\Statements\Controller\VatController::generateInspectionalStatement
    methods: GET
statement_vat_display:
    path: /dph/kontrolni_hlaseni/{id}
    defaults:
        id:
    controller: \App\Statements\Controller\VatController::displayInspectionalStatement
