accounts_api_search:
    path: /api/accounts/search
    controller: \App\Controller\AccountController::apiSearch
    methods: POST
contacts_api_search:
    path: /api/contacts/search
    controller: \App\Controller\ContactController::apiSearch
    methods: POST
transactions_list:
    path: /
    controller: \App\Controller\TransactionController::list
    methods: GET
transactions_submit:
    path: /
    controller: \App\Controller\TransactionController::submitForm
    methods: POST
